name: Product linting

on:
	push:
		branches:
			- main
	pull_request:

jobs:
	editorconfig:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v4
			- uses: oven-sh/setup-bun@v2
			- run: |
				bun run lint:editorconfig
